# Configuration for freegin-ai
#
# RECOMMENDED: Use encrypted credential storage instead:
#   freegin-ai --init    (interactive wizard)
#   freegin-ai add-service <provider>
#
# This file serves as a template for ~/.config/freegin-ai/config.toml
# API keys in this file are NOT encrypted. Use the commands above for secure storage.

[server]
host = "127.0.0.1"
port = 8080

[database]
# Override via DATABASE_URL environment variable if needed
# Default: sqlite://~/.local/share/freegin-ai/app.db
url = ""

# Provider API keys (leave empty to use encrypted storage)
# Get API keys from the URLs listed below

[providers.groq]
# Sign up: https://console.groq.com/keys
# Free tier: 1,000 requests/day (70B models), 14,400 requests/day (8B models)
api_key = ""
api_base_url = "https://api.groq.com/openai/v1"

[providers.deepseek]
# Sign up: https://platform.deepseek.com/api_keys
# Pricing: Pay-as-you-go ($0.028-$2.19 per million tokens, very low cost)
api_key = ""
api_base_url = "https://api.deepseek.com"

[providers.together]
# Sign up: https://api.together.xyz/settings/api-keys
# Pricing: $5 credit purchase required (free tier ended Aug 2025)
api_key = ""
api_base_url = "https://api.together.xyz/v1"

[providers.google]
# Sign up: https://makersuite.google.com/app/apikey
# Free tier: 100 requests/day (Gemini 2.5 Pro)
api_key = ""
api_base_url = "https://generativelanguage.googleapis.com/v1beta"

[providers.cloudflare]
# Sign up: https://dash.cloudflare.com/profile/api-tokens
# Create API token with Workers AI Read/Write permissions
# Free tier: 10,000 Neurons/day (~100-10K requests depending on model), 100K requests/day platform limit
# Note: api_base_url must include your account ID: https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/ai/v1
api_key = ""
api_base_url = ""

[providers.cerebras]
# Sign up: https://cloud.cerebras.ai/
# Free tier: 1 million tokens/day (ultra-fast inference)
api_key = ""
api_base_url = "https://api.cerebras.ai/v1"

[providers.mistral]
# Sign up: https://console.mistral.ai/
# Free tier: Available with rate limits
api_key = ""
api_base_url = "https://api.mistral.ai/v1"

[providers.clarifai]
# Sign up: https://clarifai.com/login (then go to Settings → Security to create PAT)
# Free tier: 1,000 requests/month
# Note: Requires Personal Access Token (PAT)
api_key = ""
api_base_url = "https://api.clarifai.com/v2/ext/openai/v1"

[providers.github_models]
# Sign up: https://github.com/settings/tokens
# Free tier: 50-150 requests/day (depending on GitHub Copilot plan)
# Note: Requires GitHub Personal Access Token with models:read scope
api_key = ""
api_base_url = "https://models.inference.ai.azure.com"

[providers.openrouter]
# Sign up: https://openrouter.ai/keys
# Free tier: 50 requests/day for :free models (aggregator)
api_key = ""
api_base_url = "https://openrouter.ai/api/v1"

[providers.hugging_face]
# Sign up: https://huggingface.co/settings/tokens
# Free tier: Rate-limited serverless API
api_key = ""
api_base_url = "https://api-inference.huggingface.co"

[providers.openai]
# Sign up: https://platform.openai.com/api-keys
# Pricing: Pay-as-you-go (no free tier, requires payment method)
api_key = ""
api_base_url = "https://api.openai.com/v1"

[providers.anthropic]
# Sign up: https://console.anthropic.com/
# Pricing: Pay-as-you-go (may have initial free credits)
api_key = ""
api_base_url = "https://api.anthropic.com"

[providers.cohere]
# Sign up: https://dashboard.cohere.com/api-keys
# Free tier: Available for experimentation
api_key = ""
api_base_url = "https://api.cohere.ai"